### ISSUE TITLE
[3.0.0] Chrome Debugging does not work if you use Sync APIs / Invariant violation: Calling synchronous methods on native modules is not supported in Chrome

### ISSUE THREAD

**Issue by Johan-dutoit** [react-native-community/react-native-device-info#776] opened 2019-09-11 13:49 UTC
As per the title, I get this when debugging on an iOS simulator (yet to try android, but assume it would be the same).

![image](https://user-images.githubusercontent.com/1611055/64702925-5dcd3c80-d4a3-11e9-8f05-a0c431a01070.png)

**Comment by mikehardy** [comment] 2019-09-11 13:51
Dang - and the reason we went away from constants is because app init was taking a long time (c.f. getUserAgent). This is a problem that needs thought.

I don't personally use a debugger (strange but true) thus had not noticed at all, and this doesn't affect me (your current maintainer) but I recognize it's important to many.

I'm open to any suggestions.

**Comment by mikehardy** [comment] 2019-09-11 13:56
I will say that I'm happy to release a breaking 4.0 or whatever if a solution is proposed that is workable for the synchronous use case. Perhaps the compromise is that only certain items are exposed synchronously, are fetched as constants, and the rest is async only. Then we just categorize which APIs get the constants + sync API treatment with sensitivity to startup time and it's good enough?

**Comment by mikehardy** [comment] 2019-09-11 14:12
In chatting with @Johan-dutoit it appears this only happens if you use the sync APIs - if your app is async-only APIs then chrome devtools should be fine?

I will add a mention of this to the docs, and that makes me think that the compromise strategy of loading a few things as constants underneath the sync APIs and having the rest (the not likely to be used at app startup items) be "dangerous" might be the best we can do to balance my desire to support sync use case at startup, and debugging, and fast init time.

**Comment by MakhouT** [comment] 2019-09-18 08:56
Having the same issue. Don't really know how to help as I really don't know what's happening.

**Comment by mikehardy** [comment] 2019-09-18 14:09
@MakhouT if you use the debugger, and you touch a xxxSync() method, the debugger will fail. If you want to use the debugger currently, you must not use any xxxSync() methods. That means you need to convert to a fully async style and if there are items you need at startup then before you create your App and display your root view, you need to fetch those items during bootstrap and the app creation / root view display needs to be in a .then() after you've got the items you need.

I recognize this is painful - being fully async on critical items during bootstrap - which is why Sync() APIs exist but they blow up the debugger, which is why I propose a pragmatic solution of making a few select items available via constants (which are synchronous) again but I haven't made that PR yet.

That's all the info I've got. Hope it helps.

**Comment by TimMun** [comment] 2019-09-20 05:21
FWIW this is my workaround in my app, basically following the above comments. In short, when my app's root component mounts, I throw up a loading screen while I populate my needed constants, then when that is finished I render the rest of my app.

First I create a `deviceInfo.js`:

```
// deviceInfo.js
import DeviceInfo from 'react-native-device-info'

var output = {}

exports.populateDeviceInfo = async () => {
  output.isEmulator = await DeviceInfo.isEmulator()
  output.version = await DeviceInfo.getVersion()
 // ... and whatever else you may need
}

export default output
```


Then in my AppContainer.js (my root component). I have some stuff relating to redux below but obv adjust it to whatever your app views should be.

```
// (import your components, etc)
import { populateDeviceInfo } from './deviceInfo'

export default class AppContainer extends Component {

  state = {
    deviceInfoLoaded: false
  }

  componentDidMount = async () => {
    await populateDeviceInfo()
    this.setState({ deviceInfoLoaded: true })
  }

  render() {
    return (
      <Provider store={store}>
        <PersistGate loading={<LoadingView />} persistor={persistor}>
          { this.state.deviceInfoLoaded ? <App /> : <LoadingView /> }
        </PersistGate>
      </Provider>
    )
  }
}
```

And then afterwards I can just `import DeviceInfo from './deviceInfo'` where I need it and use the populated constants. I didn't have that many constants to load, nor did they take a huge amount of time, so this worked for me.

**Comment by mikehardy** [comment] 2019-09-20 13:24
That's fantastic, thanks especially for showing working code. That is about exactly what I'd expect to handle a fully async style for things you need before first render, and I'm guessing many (like myself) weren't sure how to handle it so cleanly.

**Comment by kirillpisarev** [comment] 2019-09-20 14:12
@TimMun Actually there could be the cases when this approach won't work. For example when you use the lib within some code that is executed during the app startup. E. g. when you create a StyledComponent object and use `isTablet()` function inside. So this code won't wait until the `populateDeviceInfo` object is populated.

**Comment by mikehardy** [comment] 2019-09-20 14:19
I personally had some code that was ill-advised but called DeviceInfo items in the constructor on objects that had a singleton pattern (exported result of MySingleton.getNewInstance() which calls the constructor, which calls DeviceInfo) so just import statements were triggering things. So I do sympathize with the desire for Sync() APIs and for making those work with the debugger.

But in general each example of how to handle things slightly better gets people to consume the API more async which I think is more javascript-idiomatic

**Comment by JensDebergh** [comment] 2019-09-25 14:36
@TimMun 

I understand why the API has been rewritten to become async and reduce app boot time but to me it's just weird I need asynchronous calls for constants that are readily available on the device.

Imagine programming in javascript and writing this to fetch a constant:

```
const MY_CONSTANT_VARIABLE = 1

const fetchMyConstant  = Promise.new(() => {
 resolve(MY_CONSTANT_VARIABLE)
}, reject) 
```

Writing promises like this for constants is just weird but that's what is essentially happening right now with the rewrite to asynchronous calls.

The sync calls are a great addition but you completely lose debugging functionality for your entire app which breaks every developer team that uses `react-native-device-info`.

My point is:

All if not most of `react-native-device-info` calls are short running processes that take milliseconds to complete and send data.

Picking async calls to boost app performance in my opinion isn't the best solution to this problem. I mainly think that sending all this data over the react native bridge is the bottleneck and switching to async calls just pushes the problem down the line while adding extra complexity.

I would rather have a few extra ms of boot time then having to deal with async calls for fetching constants.

If I can help in any way let me know.

**Comment by mikehardy** [comment] 2019-09-25 14:48
`All if not most of react-native-device-info calls` - which ones? for which devices? My first cut was purist and intended to not arbitrarily decide. Just make them all async.

My experience integrating that was that it was irritating at bootstrap yes. So my second cut was to add a companion Sync API.

Only later I learned it blew up debugging. So here we are.

Pragmatically, https://github.com/react-native-community/react-native-device-info/pull/784 goes down the arbitrary "let's decide for some calls to not be async" route by restoring a few key things as constants.

For your example I'd say I can imagine writing code like that but why would I do that?

```javascript
async myUsefulFunction() {
  try {
    const myConstant = await deviceInfoCall();

     // all that other stuff useful functions
     // seemingly always relying on async stuff anyway so...


  } catch (e) {
    console.log('that sucked');
  }
}
```

Not trying to debate really. I intend to get have chrome debugging support resolved. If you want to help, work on the draft of that PR - I haven't had time to work on it yet

**Comment by JensDebergh** [comment] 2019-09-25 15:14
My example was just to demonstrate `react-native-device-info` prior to writing most functions from constants to functions.

For example:

These are declared as constants on the module:

Prior to rewrite:

https://github.com/react-native-community/react-native-device-info/blob/master/ios/RNDeviceInfo/RNDeviceInfo.m#L130

Now:

https://github.com/react-native-community/react-native-device-info/blob/41ee8c78e561ff5d689a353095e25c6b7f821218/ios/RNDeviceInfo/RNDeviceInfo.m#L98

I just think stuff like this should be declared as a constant since it's instant and should be accessible as so. Not as a function that should be waited on.

If calling all these methods in succesion is raising boot time significantly maybe we could bundle all these calls and send all info over the bridge in 1 call.

Native:

```
// EXPORT AS CONSTANT
deviceInfo: {
  systemName: self.systemName,
  bundleId: self.bundleId,
} 
```

Javascript:

```
const { systemName, bundleId } = DeviceInfo.getInfo()

// At this point you can cache all values in javascript that won't change like systemName, etc...

// Specific call for up to date battery level
const batteryLevel = await DeviceInfo.getBatteryLevel()
```

**Comment by mikehardy** [comment] 2019-09-25 15:54
did you look at the linked PR?

**Comment by retyui** [comment] 2019-09-26 08:01
Have this same problem

**Comment by thepost** [comment] 2019-09-26 15:59
100% in agreement with @JensDebergh, very well presented. 
https://github.com/react-native-community/react-native-device-info/issues/776#issuecomment-535053950

I come from mainly a native mobile background, and think that async calls for device constants is excessive. It leads to unnecessary complexity, which is something that I'm always against. But if it doesn't impact the user (a delay of a few ms at worst), and especially if there's no clear conclusion if any delay is primarily caused by the bridge or not, it seems wise to just opt for brevity on the API level and use constants instead.

**Comment by mikehardy** [comment] 2019-09-26 17:29
This is all interesting, we are all in agreement in general, and it does nothing to move the issue forward 🤷‍♂

**Comment by JensDebergh** [comment] 2019-09-26 17:34
@mikehardy I'm able to work on the pull request this saturday but I'm only able to the iOS part. My java is terrible.

**Comment by mikehardy** [comment] 2019-09-26 17:50
tag team activate: my ios is terrible but I'm really strong at java :-)

**Comment by hellogerard** [comment] 2019-09-26 18:22
Here I came, just looking to get the updates for iPhone 11's, and walked into a hornet's nest! Programming, am i right?

This is pretty critical. Our app has core, core bootstrap code that has been running for years that would take an entire rewrite to get working with async operations. Using the sync alternatives works, but breaks the debugger, per this issue. I plan on sticking to v2.x of this package and manually working around it for iPhone 11 support. But this won't work forever.

...Here's another temporary solution: we can detect if the debugger is open. 

```js
const DEVICE_MODEL = global.__REMOTEDEV__ ? 'Debugger' : DeviceInfo.getModelSync();
```

I'm using react-native-debugger. YMMV.

**Comment by mikehardy** [comment] 2019-09-26 18:40
I like the workaround - that is potentially useful for people thanks

I don't imagine this will stay unresolved more than another week - this module was already working fine with constants (implication: I/we have code I can refer to quickly to get some constants back without the async or debugger breaking)

Quick question for anyone following along - what is your minimal set of constants you need for bootstrap to work?

There will always be APIs in this module that are async because they are so slow (lookin' at you UserAgent...) so I want to find the middle path that includes the right things as constants but leaves the rest

**Comment by hellogerard** [comment] 2019-09-26 20:27
Here are all the calls we use from this package. It's actually not as many as  I had thought.

```
DeviceInfo.getManufacturer(),
DeviceInfo.getModel(),
DeviceInfo.getSystemVersion(),
DeviceInfo.getBuildNumber(),
DeviceInfo.getUniqueID();
DeviceInfo.getVersion()
DeviceInfo.getBundleId();
```

**Comment by mikehardy** [comment] 2019-09-26 20:59
those are all included in the ones I was thinking of making constants yes - curious for other responses so I can look at the union of set

**Comment by JensDebergh** [comment] 2019-09-26 21:11
@mikehardy Can you post the list you have for properties that are going to be available as constants?

If you the list of properties I can make the changes this saturday.

**Comment by mikehardy** [comment] 2019-09-26 22:21
this is what I have in my app that I need at bootstrap

```typescript
interface EssentialDeviceInfo {
  uniqueId: string;
  model: string;
  manufacturer: string;
  systemVersion: string;
  appVersion: string;
  buildNumber: string;
  phoneNumber: string;
  bundleId: string;
}
```

**Comment by dburdan** [comment] 2019-09-26 22:45
We were able to migrate relatively easily to async, though our app isn't too complex. The main ones that took some refactoring for us were:
```ts
DeviceInfo.getUniqueID()
DeviceInfo.isTablet()
DeviceInfo.hasNotch()
```
We used the notch and tablet information in some cases to determine how to mount a component at bootstrap, such as with react-navigation. Otherwise, it was a pretty smooth refactor.

**Comment by mikehardy** [comment] 2019-09-26 22:47
Just a note to say hasNotch() isn't going anywhere right now, and I believe it could be a constant, but you might be interested in https://github.com/th3rdwave/react-native-safe-area-context - it's the real solution to all these viewable area encroachments and already works way better

**Comment by makeitsimplehk** [comment] 2019-09-27 04:07
I sugguest isTablet() also need to make as constants

**Comment by kirillpisarev** [comment] 2019-09-27 07:49
Looked at my code and found out that i also use `getBrand` method alongside with the methods specified above during the app startup.

**Comment by JensDebergh** [comment] 2019-09-27 08:14
> this is what I have in my app that I need at bootstrap
> 
> ```ts
> interface EssentialDeviceInfo {
>   uniqueId: string;
>   model: string;
>   manufacturer: string;
>   systemVersion: string;
>   appVersion: string;
>   buildNumber: string;
>   phoneNumber: string;
>   bundleId: string;
> }
> ```

The list of properties we use in our app:

```
DeviceInfo.getDeviceName()
DeviceInfo.getDeviceLocale()
DeviceInfo.is24Hour() -> +3.1.4 extracted to different library
DeviceInfo.getDeviceCountry() -> +3.1.4 extracted to different library
DeviceInfo.getTimezone() -> +3.1.4 extracted to different library
DeviceInfo.isTablet()
DeviceInfo.getMaxMemory() as (number | undefined)
DeviceInfo.getTotalMemory()
DeviceInfo.getManufacturer(),
DeviceInfo.getModel(),
DeviceInfo.getBrand(),
DeviceInfo.isEmulator(),
DeviceInfo.getSystemName(),
DeviceInfo.getSystemVersion(),
DeviceInfo.getUserAgent(),
DeviceInfo.getDeviceId(),
DeviceInfo.getUniqueID(),
DeviceInfo.getBundleId(),
DeviceInfo.getBuildNumber(),
DeviceInfo.getVersion(),
DeviceInfo.getApplicationName(),
```

**Comment by mikehardy** [comment] 2019-09-27 13:29
@JensDebergh some of those will never be constants again, e.g. UserAgent, probably the memory ones. Can you separate out the ones that are vital to your bootstrap?

**Comment by JensDebergh** [comment] 2019-09-27 13:37
My bad I just listed everything we do on boot but obviously not all of these are required. 

Just as you said `UserAgent` and `Memory` can be skipped in our app aswell. We just check these to allow certain animations.

Maybe we should list the obvious performance bottleneckcalls and convert the rest to constants again?

**Comment by ethanneff** [comment] 2019-09-27 13:39
It would be nice if `isEmulator()` could make the list.

**Comment by mikehardy** [comment] 2019-09-27 13:41
I want to have the opposite stance - constants for what is needed, async (with a sync mirror as workaround for edge cases). I think the real bootstrap need is pretty low but the API surface area here is large and will grow

@ethanneff I'll see about isEmulator but I have a PR that makes that call pretty comprehensive - #721 - and I don't know how it could be fast, so likely not, at least in the first cut

**Comment by ethanneff** [comment] 2019-09-27 13:45
@mikehardy never mind the need for `isEmulator()`. I used to use it to turn off `useNativeDriver` for animations, but this appears to no longer be broken with the latest React Native version.

**Comment by mikehardy** [comment] 2019-09-27 14:03
inexorable forward progress :-) good stuff @ethanneff

**Comment by JensDebergh** [comment] 2019-09-29 09:35
@mikehardy Have a look at https://github.com/react-native-community/react-native-device-info/pull/817

**Comment by jasperkuperus** [comment] 2019-09-29 14:51
Ah, so I really need the `model` to be available directly. (Using it to distinguish a certain style, which is created on import, so async won't work). For now I've downgraded to `2.x`. Just chiming in to let you guys know I'd appreciate `model` being marked as an essential.

**Comment by mikehardy** [comment] 2019-09-29 18:20
Thanks @JensDebergh I'm not sure if I will get to it today, but I will try, and it's definitely on the short list for review as I really want to get this knocked out and feel more solid about the v3+ experience

@jasperkuperus - model request is noted - and that's the same use case I have (device info used immediately via import chains) and I will say that if you restructure your code so that the AppContainer / Root View stuff happens as a then() in bootstrap, *and* you restructure your code so that the things you needed on import are instead done using info from a device info query etc, then it's possible. And I went down that path and then added the Sync parallel API so I get that this is unpalatable but just wanted to mention in case you were stuck on UIWebView references or something as an emergency.

**Comment by MakhouT** [comment] 2019-09-30 14:52
To answer your question @mikehardy and to drop some more insights of how the package is being used I can tell you I am in need of the following constants:
```
DeviceInfo.getDeviceType();
DeviceInfo.getUniqueID();
DeviceInfo.getModel();
DeviceInfo.getVersion();
```
I am also using a package called `applicationinsights-react-native`, they also still have a dependency on the ones above.

**Comment by mikehardy** [comment] 2019-09-30 15:04
@MakhouT thanks - those all seem sane for now. We have an iOS pull request already to make this change I'll see about an Android and Windows one shortly so we can get this sorted

**Comment by rtman** [comment] 2019-09-30 17:59
just to confirm `hasNotch` could be available as a constant?

**Comment by mikehardy** [comment] 2019-09-30 18:47
@rtman yeah it could be but you really want to move to something like this https://github.com/th3rdwave/react-native-safe-area-context

**Comment by rtman** [comment] 2019-09-30 18:52
@mikehardy I had a look at `react-native-safe-area-context` and I'm interested in it, but to be honest there's a lack of information on that package, so I'm wary to change to it yet. There's hardly any description on what it does. I'd prefer to stick with `hasNotch` if possible.

**Comment by mikehardy** [comment] 2019-09-30 18:54
Yeah - the package is new but the contributor there is a frequent react-native contributor / maintainer, and the library does what hasNotch() here *wishes* it did ;-) - this article shows how that package already correctly works with all the simulators and emulators, and even the web https://github.com/th3rdwave/react-native-safe-area-context#resources

**Comment by mikehardy** [comment] 2019-09-30 18:55
hasNotch will eventually go away here and be handled by that package once the maintainer there and I finish making sure the use cases here are easily handled etc

**Comment by rtman** [comment] 2019-09-30 18:58
@mikehardy ahh i see, ok well maybe I can get the maintainer to flesh out the readme a bit and that will satisfy my concerns.

**Comment by rtman** [comment] 2019-09-30 20:26
@mikehardy I'm not seeing any indication that `react-native-safe-area-context` allows for code to run if there is no notch, it looks to only replace `SafeAreaView`. We use `hasNotch` to apply padding to the screen when there is no notch and remove padding when there is. (I asked this question in an issue on the package, but thought you might know since you are planning on migrating `hasNotch` to this)

**Comment by JensDebergh** [comment] 2019-10-01 07:43
@rtman We do similar things with `hasNotch` for more control. Although `<SafeAreaView>` is nice you lose control of the top and bottom of your screen. 

Imagine using 2 different colors for your header & footer of a screen. You are unable to do this with this type of view. Whereas `hasNotch` gives you control to add paddings if you need it.

**Comment by KingAmo** [comment] 2019-10-01 09:25
since i use custom header in my app, I need `hasNotch` to decide the height of the  custom header in `iOS` (in `Android`  I use `StatusBar.currentHeight` to set the height)

**Comment by eXist-FraGGer** [comment] 2019-10-01 19:51
Some of this methods extremely need in Styles.
It is impossible to use them with Async style.

**Comment by plowman** [comment] 2019-10-03 03:13
I kept looking for a solution that uses this library but avoids async and promises and couldn't find one so I've forked this project to make almost all of the constants exposed without callbacks. You can [find the new project here](https://github.com/parkwithpark/react-native-device-constants). I've renamed some of the constants (e.g. `appBuildNumber` instead of the more ambiguous `buildNumber`) but it is basically the same otherwise.

If there's any interest in this, I'll create an npm module for it. Until then, you can link directly to the github project.

**Comment by mikehardy** [comment] 2019-10-03 03:23
@plowman I mean cool, but, could have done a PR that implemented it for Android and in combo with iOS we're basically done here?

**Comment by plowman** [comment] 2019-10-03 03:43
@mikehardy Sure, not opposed to trying to merge my changes into this project if that's something people are interested in.

Anyway, I figured changing this project would be a multi-week process in the best case (or you would reject my PR in the worst case), but I needed to hack together a fix sooner than that, so wanted to share for others who are in the same boat.

**Comment by mikehardy** [comment] 2019-10-03 03:54
@plowman If it looks anything like the iOS version in PR right now - https://github.com/react-native-community/react-native-device-info/pull/817 - I will merge it as soon as I have time to review and the internet will grant you virtual fame ;-)

**Comment by rtman** [comment] 2019-10-03 05:18
@plowman if you have time please look into making a pr for this.

**Comment by jbrodriguez** [comment] 2019-10-04 13:50
Here's hoping this gets solved soon, I really need DeviceInfo.getUniqueID()

**Comment by plowman** [comment] 2019-10-07 22:33
@mikehardy haha, well if internet points are involved... I might have time this week to put up a PR for Android. Can you confirm for me that the list of properties in #817 is comprehensive, i.e. does it list every property we want to expose as a constant? Or are there others?

**Comment by mikehardy** [comment] 2019-10-07 23:20
If an android code change in harmony with the existing windows one and ios one appeared that would be insta-points and insta-merged yes :-). I believe that's all we want to expose now - however - just re-adding the constants infrastructure is the actual task. Easy to add to the list if needed to get the tension right

**Comment by mikehardy** [comment] 2019-10-07 23:21
Current status is in #817 - last comments

**Comment by mikehardy** [comment] 2019-10-10 22:30
Test it please https://github.com/react-native-community/react-native-device-info/releases/tag/v4.0.1-beta.5

**Closed by mikehardy** 2019-10-10 22:31 UTC
Labels: bug, help wanted

**Comment by mikehardy** [comment] 2019-10-11 21:21
4.0.1-rc.1 is out and the migration guide is up, unless bugs are found I will release it tomorrow

https://github.com/react-native-community/react-native-device-info/releases/tag/v4.0.1-rc.1

react-native-community/react-native-device-info/wiki/V3-to-V4-Migration-Guide

Please test it, and edits / improvements to the migration guide are always welcome.

Thanks!

**Comment by MakhouT** [comment] 2019-10-13 20:15
I just noticed in the new release we are missing `DeviceInfo.getDeviceType();` This is still a Promise currently.

**Comment by mikehardy** [comment] 2019-10-13 20:37
I can see how that would be important for initial layout which is my loose criteria for constants, can you create a fresh issue for it for tracking? I can get it in a 4.0.2 for you as going from Promise to direct return is non-breaking for people I believe (where the other way is not)

**Comment by mikehardy** [comment] 2019-10-13 23:08
@MakhouT you can try the `@next` tag to get 4.0.2-rc.1 with deviceType as a constant

https://github.com/react-native-community/react-native-device-info/releases/tag/v4.0.2-rc.1

I may need to release it as a breaking change v5 - I think removing the promise is breaking, but you can use it now at least

**Comment by mikehardy** [comment] 2019-10-15 12:40
@MakhouT please report back on 4.0.2-rc.1

**Comment by MakhouT** [comment] 2019-10-15 13:02
@mikehardy Thanks for the quick reaction! I haven't had time yesterday, I will try to test it this evening or tomorrow morning. I'll definitely get back to you!

**Comment by renatoniro** [comment] 2019-10-16 19:47
@mikehardy Would it at all be possible to have getDeviceName exposed as a constant? (as in, anything impeding it from being a constant?). I'd imagine it should be pretty safe as (under normal circumstances) the device name shouldn't change between app launches?

**Comment by mikehardy** [comment] 2019-10-16 23:54
getDeviceName is backed by bluetooth on android and can actually change any time, plus going in to that system has costs I'm unsure of but it isn't like a built-in system constant, I'm not sure on that one

**Comment by renatoniro** [comment] 2019-10-17 15:33
Thanks for the explanation @mikehardy - that makes more sense as to why it is implemented that way.

**Comment by MakhouT** [comment] 2019-10-19 22:04
@mikehardy Sorry that it took a bit longer than promised. I was able to test it and it works perfectly as expected! Thanks!
Any more chances we can take into V5?

**Comment by mikehardy** [comment] 2019-10-19 22:19
Probably not, but I'm not afraid of major versions, I'm only afraid of accidentally breaking people in a non-major, so no need to wait much. I'll get this packed up and a v5 out probably by Monday

**Comment by MakhouT** [comment] 2019-10-19 22:23
Perfect! Thanks!

**Comment by mikehardy** [comment] 2019-10-24 11:47
@acro5piano submit a PR please, I can merge it in if it's got all the associated "stuff" (type files, README etc)

**Comment by limaAniceto** [comment] 2020-12-07 16:59
@mikehardy thank you for your work.

Just one question, a few folks mentioned it would be great if `deviceName` was available as a constant. Is there any specific reason not to have it?

**Comment by mikehardy** [comment] 2020-12-07 17:05
good question - device name is not a constant in reality, it may change (e.g., rename your android in bluetooth), the API should reflect that - it is reality

**Comment by limaAniceto** [comment] 2020-12-07 17:17
> good question - device name is not a constant in reality, it may change (e.g., rename your android in bluetooth), the API should reflect that - it is reality

Sorry @mikehardy , after re-reading above I noticed you had already replied to that question so I deleted my comment : )

I appreciate you getting back to me so quickly!

Anyway I understand the folks above difficulty as I'm facing it as well. The case is: Styling headers depending on device (making use of libraries like react-navigation). As you can't add the async wrappers or use state, you can't style the Header.

This is definitely not an easy one 😢

**Comment by mikehardy** [comment] 2020-12-07 17:23
For those exact cases we have the Sync calls, but then you can't use the Chrome debugger. It's not an easy thing.
If it really is a fundamental need and you've got no valid workaround it is open source, patch-package makes carrying a local mod pretty easy and you can just add it to constants for your project, knowing that it may change in reality but you're willing to accept it in order for styling to somehow be based on a device name

**Comment by AndrinGautschi** [comment] 2021-07-26 13:04
Hey. I faced this issue today with the `getFontScaleSync()` method. Is it possible to detect if Chrome Debugging is running and either do this request or replace it with a self defined constant? That would help immensely.

**Comment by mikehardy** [comment] 2021-07-26 19:32
No @AndrinGautschi - I really do not want to gum up the package with chrome debugger-not-chrome-deubugger code. We have sync methods, we have async methods, it's open source, use what you need to use for your use case, patch at will as needed please
