### ISSUE TITLE
'React/RCTUtils.h' file not found in RNDeviceinfo.m even if react native link 

### ISSUE THREAD

**Issue by cakesoft-shivani** [react-native-community/react-native-device-info#897] opened 2019-11-21 09:37 UTC
## Summary

react-native-device-info = 5.3.1V
react-native = 0.59.5V

## Current behavior

I am using device info in my app but its showing me error 
'React/RCTUtils.h' file not found

**Comment by mikehardy** [comment] 2019-11-21 12:37
Run this script from the repo: https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example-rn59.sh and see if you can reproduce it. Last time I checked RN59 built fine

Duplicate of #887 #701 #786 and quite a few others from a simple search https://github.com/react-native-community/react-native-device-info/issues?q=is%3Aissue+sort%3Aupdated-desc+RCTUtils+is%3Aclosed

**Closed by mikehardy** 2019-11-21 12:37 UTC
