### ISSUE TITLE
Support isEmulator as a constant

### ISSUE THREAD

**Issue by dexterlohnes** [react-native-community/react-native-device-info#919] opened 2019-12-17 18:55 UTC
# Feature Request

It would be great if `isEmulator` were supported as a DeviceInfo constant.

## Why it is needed

I use this on a project for a client at startup as part of our configuration process. As it stands, everything works fine on iOS but on Android I get an error if I use `isEmulatorSync()` during config. 

## Possible implementation

I really don't know, but I imagine it would be somewhat similar potentially to the other constant translations you've recently done. I'm not sure if checking if the device is an emulator is especially difficult or strange in this regard.

### Code sample

```
DeviceInfo.isEmulator()
```

**Comment by mikehardy** [comment] 2019-12-17 19:35
Strange. I see no reason isEmulatorSync would behave differently for iOS or Android. They both go native, so either both should work or both should fail. The only difference between xxxSync() and xxx() APIs are that xxxSync won't work with the Chrome debugger. There's not her difference really.

So I'd look to see why android is failing with that one.

Otherwise, I could see that one being exposed as a constant I suppose. On Android it does not matter as much but on iOS the Simulators are a mediocre emulation. I don't believe there is a way to convert it in a backwards-compatible way so it'd be a breaking change. Before I do that I'd really like to hear the results of the investigation I mention above

**Comment by mikehardy** [comment] 2020-01-10 20:24
This is actually a dupe of #879 and I've got that one labeled up already with more info

**Closed by mikehardy** 2020-01-10 20:24 UTC
