### ISSUE TITLE
What is the best practice of using async DeviceInfo.hasNotch() for styling

### ISSUE THREAD

**Issue by nenjamin2405** [react-native-community/react-native-device-info#831] opened 2019-10-08 04:01 UTC
# Question

Previously I used RNDeviceInfo version `2.3.2` and although `DeviceInfo.hasNotch()` is marked as async in the document, I can still use it as synchronous way to apply style for my components like this:

`marginTop: DeviceInfo.hasNotch() ? GAP.medium : 0`

However, when I upgrade this lib to version `3.1.4` (to detect iphone 11, 11 Pro, 11 Pro Max, ...), `DeviceInfo.hasNotch()` is now async so the above code is not working anymore.

So my question is, what is the best practice of using async DeviceInfo.hasNotch() for styling in RN?

**Comment by mikehardy** [comment] 2019-10-08 04:07
Honestly - my best advice is to do one of two things:

1- if you are not using the Chrome debugger, upgrade and use hasNotchSync() for now (but if you are using the debugger it will break #776)
2- wait for just a couple more days, and a few items that are important at startup (where it is very difficult to be async) will be constants again available synchronously (like the xxxSync() APIs that are available in v3) but without causing bug #776 

I'm going to close this not because it's not a legit issue - the PR #817 is targeted at easing the pain, just that you should probably just subscribe there and wait for v4 which will be out in a bit

**Comment by nenjamin2405** [comment] 2019-10-08 04:12
@mikehardy Thanks a lot for your advice, I will use the option 1 first and wait for v4

**Comment by mikehardy** [comment] 2019-10-10 22:31
Test it please https://github.com/react-native-community/react-native-device-info/releases/tag/v4.0.1-beta.5

**Closed by mikehardy** 2019-10-10 22:31 UTC

**Comment by nenjamin2405** [comment] 2019-10-11 04:39
Hi @mikehardy, I just installed the package`"react-native-device-info": "^4.0.1-beta.5"`, and then go to /ios, pod install, and test it but it's not working, the `hasNotch()` return false for my iPhone 11 emulator. I also tested the `isTablet()` for the iPad Pro (11 inch), it's not working also

**Comment by mikehardy** [comment] 2019-10-11 04:41
@nenjamin2405 indeed! Thanks to another community member this issue was pointed out with a code reference, I confirmed it and just published beta.6 with a fix - literally 1 minute ago. Can you try that one?

**Comment by nenjamin2405** [comment] 2019-10-11 04:53
@mikehardy It's now working also :(, just upgraded to `"react-native-device-info": "4.0.1-beta.6"`. I just want to confirm that I don't need to do any hacky method to preload the lib to make it work right?

**Comment by mikehardy** [comment] 2019-10-11 04:54
You may need to do `npx react-native-clean-project` in your project root, and answer yes only to the "wipe iOS build" question, no to everything else then rebuild. I'll double-check on my end as well, it worked in testing for this specific problem but perhaps the publish failed for some reason

**Comment by mikehardy** [comment] 2019-10-11 05:02
I just finished double-checking the example app after carefully cleaning local state per my recommendation above, on beta.6 it definitely works whereas on beta.5 it did not - simulator and emulator. So hopefully the react-native-clean-project module can get you through it - it should work

**Comment by nenjamin2405** [comment] 2019-10-11 05:11
@mikehardy I can confirm that hasNotch() is working now, but the `isTablet()` is returning false for the iPad Pro (11 inches) emulator

**Comment by mikehardy** [comment] 2019-10-11 05:44
Oh this is a tricky one! I can reproduce it - but! It reminds me that I've seen it before. So this module takes the default react-native template for it's example. And that template sets the 'Deployment Info' Target Device to just 'iPhone' and not 'iPad' in the General settings in Xcode. So it doesn't build for tablet, and even if you run it on a tablet like that it works like a phone (small screen with big black bars on sides, isTablet == false). If you tick the iPad checkbox, you should see isTablet == true and the UI fills the screen.

But even here that didn't work because of this: https://github.com/react-native-community/react-native-device-info/blob/v4.0.1-beta.6/ios/RNDeviceInfo/RNDeviceInfo.m#L66 :scream: - that was not supposed to make it into a formal commit.

beta.7 is just published with the fix

**Comment by mikehardy** [comment] 2019-10-11 05:45
thank you so much for testing this, by the way! directly improved the quality - I would have missed at least one of these in my testing I'm sure

**Comment by nenjamin2405** [comment] 2019-10-11 06:17
@mikehardy No problem!! Awesome!! Now both the iPhone and iPad are displaying well with react-native-device-info beta7's logic. Thanks a lot!!!

**Comment by mikehardy** [comment] 2019-10-11 21:21
4.0.1-rc.1 is out and the migration guide is up, unless bugs are found I will release it tomorrow

https://github.com/react-native-community/react-native-device-info/releases/tag/v4.0.1-rc.1

react-native-community/react-native-device-info/wiki/V3-to-V4-Migration-Guide

Please test it, and edits / improvements to the migration guide are always welcome.

Thanks!

**Comment by ralph-dev** [comment] 2019-10-19 16:40
@mikehardy 
![image](https://user-images.githubusercontent.com/7469722/67148435-8f3ce300-f26d-11e9-8e9f-ceea60d0ffd2.png)
Seems like it's trying to make it lowercase of an undefined value on line 767.
Here is the code where it is erroring.

```
import DeviceInfo from 'react-native-device-info';

let result = null;

/**
 * Return true if device is iPhone X series
 * @returns {boolean}
 */
export default function () {
  if (result === null) {
      result = DeviceInfo.hasNotch();
  }
  return result;
}
```

**Comment by mikehardy** [comment] 2019-10-19 17:07
@ralph-dev  Line 767 of what file? What version are you on? That is not an actionable bug report. Please open a new one, including all the information you'd want if you were troubleshooting your own report

**Comment by ralph-dev** [comment] 2019-10-19 17:18
Yep, sorry about that. I've debugged it myself. It seems that the module wasn't linking properly. I had to run these commands to fix it.

`
killall -9 node
npm start --reset-cache
and run from XCode
`
If it comes up again and is consistently causing issues I'll formalize a proper report. Hopefully, this helps anyone else who encounters this though!
