### ISSUE TITLE
'React/RCTUtils.h' file not found inRNDeviceinfo.m

### ISSUE THREAD

**Issue by Hanf92** [react-native-community/react-native-device-info#887] opened 2019-11-12 13:29 UTC
# Bug

I did the update of react-native version 0.61.4 (starting from 0.60) and compiling IoS goes wrong.
I don't use Pod, i use autolinking.
I tried to unlink react-native-device-info and manually linking it but nothing has changed.

## Environment info

React native info output:

```bash
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 25.41 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.1.0 - /usr/local/bin/node
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5314842
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

```

Library version: 5.3.0

## Steps To Reproduce

Warning: version react-native must be >= 0.61.x
1. Add react-native-device to react native project 
2. Use manual linking or auto linking, it's the same
2. build for ios

**Comment by mikehardy** [comment] 2019-11-12 19:05
auto-linking == you use pods
Do not forget to run pod install
You can follow the steps here to see exactly how to integrate and build correctly, it is how we generate the actual example in the repo: https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example.sh#L35

**Comment by cjadhav** [comment] 2019-11-13 05:42
Hi @mikehardy,

Thanks for the help. But it's not solving the issue.
For me everything was working until I update Xcode 11.2.1.
It was working on Xcode 10.3.

Please can you help regarding that.

/cc @Hanf92

**Comment by RaquelCasadoDias** [comment] 2019-11-13 10:25
Any news on that? I ran into the same issue. I had it working fine but just updated my project from react-native 0.58 to 0.61. The updated worked well for my other dependencies and for Android but I'm stuck on this for ios build.

**Comment by mikehardy** [comment] 2019-11-14 03:27
I'm sorry, I wish I could help - I maintain things because I actually like fixing things. But if you reference the example construction script I linked above (and which I use to construct the example for this repo) it works. So I can't reproduce it - I'm not sure what is going on, but it seems to work for me

**Comment by fattahmuhyiddeen** [comment] 2019-11-15 10:17
i also had exactly the same issue. rn 61.4

**Comment by asifalikhokhar** [comment] 2020-03-23 13:37
I m having same issue, RN 0.61.5

**Comment by mikehardy** [comment] 2020-03-23 13:52
There is no issue compiling this module that I can reproduce. We provide an example that demonstrates it working. If you can demonstrate a minimal reproducible example (publish it on github) based on the example that shows the failure, open a new issue to report it. Closing this until someone provides a reproduction.

**Closed by mikehardy** 2020-03-23 13:52 UTC
Labels: cant-reproduce, ios

**Comment by nishanBende** [comment] 2020-04-16 07:14
This could happen if RNDeviceInfo project is not removed from the Libraries directory after upgrading to 0.61.

**Comment by fortinmike** [comment] 2020-12-02 18:36
For me, the fix was to remove the reference to react-native-device-info's `xcodeproj` (RNDeviceInfo.xcodeproj) from my custom Xcode project. No need to remove anything on disk. I had to do this for a couple other dependencies I had in my project.
