### ISSUE TITLE
UIWebView in Device Info is now deprecated/Won't pass review

### ISSUE THREAD

**Issue by iAmHarmon** [react-native-community/react-native-device-info#759] opened 2019-08-29 22:30 UTC
# Bug

Uploading an iOS app with RNC Device Info library to the App Store is prohibited. UIWebView used in package is no longer allowed per App Store rules. See email below.

> Dear Developer,
>
>We identified one or more issues with a recent delivery for your app, "MyApp" 2.2.0 (3). Your delivery was successful, but you may wish to correct the following issues in your next delivery:
>
>ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
>
>After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.
>
>Best regards,
>
>The App Store Team

## Environment info

React native info output:

```bash
React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 1.29 GB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.3 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.0
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.3 
      react-native: ^0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Library version: 2.3.2

## Steps To Reproduce

1. Upload RN project to the App Store that uses RNC Device Info library
2. Get email from Apple

Describe what you expected to happen:

1. Upload RN project to the App Store that uses RNC Device Info library
2. Successfully pass App Store review

## Reproducible sample code

I don't think this is necessary since it's it's in the RNDeviceInfo.m file. Please help!

**Comment by mikehardy** [comment] 2019-08-30 01:40
Duplicate of #756, fixed in #757, will release in v3. Please search

**Closed by mikehardy** 2019-08-30 01:40 UTC

**Comment by mikehardy** [comment] 2019-08-30 01:46
worth noting this is a **warning** they are still accepting these apps

Our (@react-native-community) best guess is that they won't stop accepting it until iOS13 is out at least, and maybe some after that. Either way this will be fixed and released shortly.

**Comment by iAmHarmon** [comment] 2019-08-30 06:29
Sorry for posting a duplicate. I must've been searching the wrong thing. This is the first app I'm releasing and the wording looked like they wouldn't be accepting apps that utilized the UIWebView library. I appreciate the help!

________________________________
