### ISSUE TITLE
Lint Error Android Build

### ISSUE THREAD

**Issue by adunn511** [react-native-community/react-native-device-info#325] opened 2018-02-13 14:37 UTC
## Summary

when running :react-native-device-info:lint I get an error. Originally it was complaining about RNDeviceModule.java overriding or implementing a deprecated API, but I can't reproduce that error. I have attached the lint results print out.

|             |     |
| ----------- | --- |
| Version     | 0.15.2  |
| Affected OS | ?   |
| OS Version  | ?   |

**Comment by adunn511** [comment] 2018-02-13 15:15
[Lint Report.pdf](https://github.com/rebeccahughes/react-native-device-info/files/1720388/Lint.Report.pdf)

**Comment by machour** [comment] 2018-02-13 15:27
Hi @adunn511 and thank you for reporting this.

I think that the deprecated methods are the one I introduced in [this commit](https://github.com/rebeccahughes/react-native-device-info/commit/e484701ea4e4d5437201d1a414c569c4968743f1) as a quickfix for #318

**Comment by adunn511** [comment] 2018-02-13 15:45
okay, I think there's another issue with gradle versions as attached in the lint report.

**Comment by sytolk** [comment] 2018-05-04 12:05
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-device-info:lint'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  
  Errors found:
  
  /home/stanimir/structmedia/triplogapp/TripApp/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:64: Error: Missing permissions required by WifiManager.getConnectionInfo: android.permission.ACCESS_WIFI_STATE [MissingPermission]
        this.wifiInfo = manager.getConnectionInfo();
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/stanimir/structmedia/triplogapp/TripApp/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:295: Error: Missing permissions required by TelephonyManager.getLine1Number: android.permission.READ_PHONE_STATE or android.permission.READ_SMS or android.permission.READ_PHONE_NUMBERS [MissingPermission]
        constants.put("phoneNumber", telMgr.getLine1Number());
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/stanimir/structmedia/triplogapp/TripApp/node_modules/react-native-device-info/android/build.gradle: Error: All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 25.2.0, 23.0.1. Examples include com.android.support:support-compat:25.2.0 and com.android.support:appcompat-v7:23.0.1 [GradleCompatible]

```

**Comment by SatishAshokMahajan** [comment] 2018-07-05 14:23
Getting same error as mentioned by @sytolk. Any suggestions?

**Comment by adunn511** [comment] 2018-07-06 13:48
in the AndroidManifest.xml those permissions need to be added above the <application> tag. I did it locally and it resolved those issues, but I kept getting a mismatch with gradle versions, so I made my own stuff to use since I only needed a few things. Hope this helps

**Comment by sytolk** [comment] 2018-07-06 15:38
@adunn511 you not need to add those permissions (if you not use READ_PHONE_NUMBERS in you App) I think the true fix for this is to suppress Lint warnings in react-native-device-info build.gradle something like this:
```
android {
      lintOptions {
          abortOnError false
      }
  }
```

**Comment by adunn511** [comment] 2018-07-06 16:03
@sytolk that’s not true the linter for the package picks that up since there are functions that need those permissions to execute, thus causing builds to fail. I use an automated pipeline and it runs the linter for this package, I’m not using those but it still fails. Adding that to the build.gradle will just suppress all lint errors. If the owners of this are okay with that I wouldn’t be opposed to that being added so I could use this :)

**Comment by adunn511** [comment] 2018-07-06 16:04
I meant add those to permissions in the manifest for this package not at the app level

**Comment by sytolk** [comment] 2018-07-06 20:35
@adunn511 if READ_PHONE_NUMBERS permission is added in Manifest for this lib. Manifest merger will set this permission in your app too. And the PlayStore users that install the App need to accept READ_PHONE_NUMBERS permission from your fake App :) I thing this is the worst thing that suppress Lint warnings ;)

**Comment by rayj10** [comment] 2018-08-15 02:39
Hi, I'm getting similar problem with build warning:
```
Configure project :react-native-device-info
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (25.0.2) is ignored, as it is below the minimum supported version (27.0.3) for Android Gradle Plugin 3.1.3.
Android SDK Build Tools 27.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :react-native-device-info:compileDebugJavaWithJavac
Note: C:\Users\Admin-ESS\Absent\node_modules\react-native-device-info\android\src\main\java\com\learnium\RNDeviceInfo\RNDeviceModule.java uses or overrides a
deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
the first warning: not sure why it is still recognized as v25.0.2 though although there is already this bit on app level gradle:
```
android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        applicationId "com.absent"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
```
I thought RN Device Info's gradle already checked if project has specified the buildtoolversions?

also, I'm complete noob when it comes to config like these, so just wanna make sure, if I change the `compile` syntax into `implement` on RN Device Info's gradle, would that solve the second warning?

**Comment by kobi963** [comment] 2018-10-16 14:53
any update on this one?

**Comment by vinayan3** [comment] 2018-12-19 07:38
I'm also experiencing issues with aborting on a lint error for missing permissions. For the app I am building I do not want to request those permissions without needing them. The patch I have added to `android/build.gradle` is 
```
    lintOptions {
       warning 'InvalidPackage', 'MissingPermission'
    }
```

**Comment by lorenc-tomasz** [comment] 2019-03-13 11:37
Any update on this?

**Comment by machour** [comment] 2019-03-13 11:40
@lorenc-tomasz nope, hints: the issue is still open, and labeled with "help wanted".
Feel free to make a PR.

**Comment by mikehardy** [comment] 2019-03-13 14:51
@lorenc-tomasz sometimes it takes less time to make a PR than to comment even...

**Comment by lorenc-tomasz** [comment] 2019-03-13 15:12
sometimes... ;) The depracations I saw is about GCM and formatter.formatipaddress. Nothing big at the moment.

**Comment by mikehardy** [comment] 2019-03-13 16:06
@lorenc-tomasz  ha - in the "test first, *then* post frisky comments" department, it appears that build.gradle needed some minor library version specifications before lint was truly happy anyway. I updated my PR after verifying that `./gradlew :react-native-device-info:lint` actually passes in the example app from this repo, with the changes that fed into the PR. Should work

**Closed** 2019-03-13 17:32 UTC
Labels: android, bug, help wanted

**Comment by machour** [comment] 2019-03-13 17:38
react-native-device-info 0.29.1 published 🎉

**Comment by lorenc-tomasz** [comment] 2019-03-15 09:48
Version 1.0.0:

> Task :react-native-device-info:compileReleaseJavaWithJavac
Note: /xyz/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by mikehardy** [comment] 2019-03-15 13:27
Did you try - Xlint deprecated? I can't tell from your comment if this is a report of success or requests for help

**Comment by zi6xuan** [comment] 2019-03-26 04:49
```
afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                lintOptions {
                    abortOnError false
                }
            }
        }
    }
```
This allows you to modify the configuration of all projects
