### ISSUE TITLE
Google deprecating install_referrer intent broadcast

### ISSUE THREAD

**Issue by msalpietro** [react-native-community/react-native-device-info#909] opened 2019-12-11 15:38 UTC
# Bug

Google is deprecating the install_referrer intent broadcast. Should update package to use new API if needed.

https://android-developers.googleblog.com/2019/11/still-using-installbroadcast-switch-to.html

## Environment info

N/A

Library version: 5.3.1

## Steps To Reproduce

N/A

## Reproducible sample code

N/A

**Comment by raedhellal** [comment] 2019-12-11 15:58
this is not a bug it is a feature @msalpietro.
Steps to migrate to the referrel library in:
https://developer.android.com/google/play/installreferrer/library.html

**Comment by msalpietro** [comment] 2019-12-11 16:01
I would agree. Thanks.

**Comment by jacargentina** [comment] 2019-12-11 16:36
Hi, i dont get it: i'm  not interested on anything about this install referrer thing; but i cant see clearly explained why should i adopt that library? I'm confused. Any advice?

**Comment by kc-paymi** [comment] 2019-12-11 17:08
> I would agree. Thanks.

Sorry but could you please let me know how do you plan to update the referrer library inside the device info library ? Won't that require us to make these changes to our app every time we set up a new project ? 
I thought you were right in pointing out that the API needs to be updated from the library maintainers in order for all apps to migrate to the new Referrer API.

**Comment by msalpietro** [comment] 2019-12-11 17:28
We're using the react-native-device-info package but not using the getInstallReferrer method so I haven't actually looked at how the changes would be implemented. I opened this purely because we received a notice from the play store that the install_referrer intent broadcast is being deprecated.

**Comment by mikehardy** [comment] 2019-12-11 17:39
It does look like there is something to know, but let me note that while I do a lot here, all of us are the maintainers. I have limited time and would love :pray:  a PR that implemented the required API movement here. Possibly as a new API name in this library (since it seems it would require a new dependency for those that want it - which is not everyone). They say "cost of adoption is low" so hopefully it's an easy PR for someone...

**Comment by carloscuesta** [comment] 2020-02-03 09:34
Should we close this issue since #947 was merged ? @mikehardy

**Comment by mikehardy** [comment] 2020-02-03 12:35
yeah - closing and about to release now

**Closed by mikehardy** 2020-02-03 12:35 UTC
Labels: Good First Issue!, android, feature-request, help wanted
