### ISSUE TITLE
Multiple files not found after install

### ISSUE THREAD

**Issue by souljacker** [react-native-community/react-native-device-info#870] opened 2019-10-29 23:40 UTC
I'm running a new react-native non expo app and after install react-native-device-info I get this error when running on android

This is on Logcat

`2019-10-29 21:16:16.087 15342-15342/? I/com.scpush: Not late-enabling -Xcheck:jni (already on)
2019-10-29 21:16:16.115 15342-15342/? W/com.scpush: Unexpected CPU variant for X86 using defaults: x86
2019-10-29 21:16:16.521 15342-15342/com.scpush D/AndroidRuntime: Shutting down VM
2019-10-29 21:16:16.522 15342-15342/com.scpush E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.scpush, PID: 15342
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbq;
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6391)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbq" on path: DexPathList[[zip file "/data/app/com.scpush-GrV8dgrblfBI-NJdTwoVmQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.scpush-GrV8dgrblfBI-NJdTwoVmQ==/lib/x86, /data/app/com.scpush-GrV8dgrblfBI-NJdTwoVmQ==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6391) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) `

And this is on the terminal

`
> Task :react-native-device-info:compileDebugJavaWithJavac
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.api.internal.zzm` was not
 found, it is required for default or static interface methods desugaring of `void com.google.android.gms.location.LocationServices$zza.setResult(java.lang.Object)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzbgm` was not found, i
t is required for default or static interface methods desugaring of `java.lang.Object com.google.android.gms.location.zzah.createFromParcel(android.os.Parcel)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.api.internal.zzm` was not
 found, it is required for default or static interface methods desugaring of `void com.google.android.gms.location.ActivityRecognition$zza.setResult(java.lang.Object)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzbgm` was not found, i
t is required for default or static interface methods desugaring of `java.lang.Object com.google.android.gms.location.zzag.createFromParcel(android.os.Parcel)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzex` was not found, it
 is required for default or static interface methods desugaring of `void com.google.android.gms.location.zzw.onLocationResult(com.google.android.gms.location.LocationResult)
`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbq` was not found, it is required for default or static interface methods desugaring of `void com.google.android.gms.location.ActivityTransitionResult.<init>(java.util.List)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbq` was not found, it is required for default or static interface methods desugaring of `void com.google.android.gms.internal.zzcha.zza(com.google.android.gms.common.api.internal.zzck, com.google.android.gms.internal.zzcgr)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzex` was not found, it is required for default or static interface methods desugaring of `boolean com.google.android.gms.location.zzv.onTransact(int, android.os.Parcel, android.os.Parcel, int)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzbgq` was not found, it is required for default or static interface methods desugaring of `com.google.android.gms.location.ActivityTransitionResult com.google.android.gms.location.ActivityTransitionResult.extractResult(android.content.Intent)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzbgo` was not found, it is required for default or static interface methods desugaring of `void com.google.android.gms.location.ActivityTransitionResult.writeToParcel(android.os.Parcel, int)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzbgm` was not found, it is required for default or static interface methods desugaring of `java.lang.Object com.google.android.gms.location.zzb.createFromParcel(android.os.Parcel)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzbgm` was not found, it is required for default or static interface methods desugaring of `java.lang.Object com.google.android.gms.internal.zzcfx.createFromParcel(android.os.Parcel)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzbgo` was not found, it is required for default or static interface methods desugaring of `void com.google.android.gms.location.GeofencingRequest.writeToParcel(android.os.Parcel, int)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzbgo` was not found, it is required for default or static interface methods desugaring of `void com.google.android.gms.location.zzaj.writeToParcel(android.os.Parcel, int)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbq` was not found, it is required for default or static interface methods desugaring of `android.os.Looper com.google.android.gms.internal.zzchz.zzaxp()`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.api.internal.zzcm` was not found, it is required for default or static interface methods desugaring of `void com.google.android.gms.internal.zzcfz.zza(com.google.android.gms.common.api.Api$zzb)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzbgo` was not found, it is required for default or static interface methods desugaring of `void com.google.android.gms.internal.zzcgl.writeToParcel(android.os.Parcel, int)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.api.internal.zzcm` was not found, it is required for default or static interface methods desugaring of `void com.google.android.gms.internal.zzcgf.zza(com.google.android.gms.common.api.Api$zzb)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbg` was not found, it is required for default or static interface methods desugaring of `boolean com.google.android.gms.internal.zzcfs.equals(java.lang.Object)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzex` was not found, it is required for default or static interface methods desugaring of `void com.google.android.gms.location.zzz.onLocationChanged(android.location.Location)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbg` was not found, it is required for default or static interface methods desugaring of `boolean com.google.android.gms.location.ActivityRecognitionResult.equals(java.lang.Object)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbj` was not found, it is required for default or static interface methods desugaring of `com.google.android.gms.tasks.Task com.google.android.gms.location.ActivityRecognitionClient.requestActivityUpdates(long, android.app.PendingIntent)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbj` was not found, it is required for default or static interface methods desugaring of `com.google.android.gms.tasks.Task com.google.android.gms.location.GeofencingClient.addGeofences(com.google.android.gms.location.GeofencingRequest, android.app.PendingIntent)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.api.internal.zzdf` was not found, it is required for default or static interface methods desugaring of `void com.google.android.gms.location.FusedLocationProviderClient$zza.zza(com.google.android.gms.internal.zzcgl)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzex` was not found, it is required for default or static interface methods desugaring of `boolean com.google.android.gms.internal.zzcgs.onTransact(int, android.os.Parcel, android.os.Parcel, int)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzbgm` was not found, it is required for default or static interface methods desugaring of `java.lang.Object com.google.android.gms.location.zzai.createFromParcel(android.os.Parcel)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzbgm` was not found, it is required for default or static interface methods desugaring of `java.lang.Object com.google.android.gms.location.zzg.createFromParcel(android.os.Parcel)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbj` was not found, it is required for default or static interface methods desugaring of `com.google.android.gms.tasks.Task com.google.android.gms.location.SettingsClient.checkLocationSettings(com.google.android.gms.location.LocationSettingsRequest)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzex` was not found, it
 is required for default or static interface methods desugaring of `void com.google.android.gms.internal.zzcgx.zza(com.google.android.gms.location.GeofencingRequest, android
.app.PendingIntent, com.google.android.gms.internal.zzcgu)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbq` was not fo
und, it is required for default or static interface methods desugaring of `com.google.android.gms.location.GeofencingRequest$Builder com.google.android.gms.location.Geofenci
ngRequest$Builder.addGeofence(com.google.android.gms.location.Geofence)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbq` was not fo
und, it is required for default or static interface methods desugaring of `void com.google.android.gms.internal.zzchk.<init>(com.google.android.gms.common.api.internal.zzn)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzbgo` was not found, i
t is required for default or static interface methods desugaring of `void com.google.android.gms.location.LocationAvailability.writeToParcel(android.os.Parcel, int)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzbgq` was not found, it is required for default or static interface methods desugaring of `com.google.android.gms.location.LocationSettingsStates com.google.android.gms.location.LocationSettingsStates.fromIntent(android.content.Intent)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzbgq` was not found, it is required for default or static interface methods desugaring of `void com.google.android.gms.location.ActivityTransitionRequest.serializeToIntentExtra(android.content.Intent)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbg` was not found, it is required for default or static interface methods desugaring of `boolean com.google.android.gms.location.ActivityTransitionRequest.equals(java.lang.Object)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Interface `com.google.android.gms.common.api.internal.zzcl` not found. It's needed to make sure desugaring of `com.google.android.gms.internal.zzchg` is correct. Desugaring will assume that this interface has no default method.
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.api.internal.zzcm` was not found, it is required for default or static interface methods desugaring of `void com.google.android.gms.internal.zzcge.zza(com.google.android.gms.common.api.Api$zzb)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Interface `com.google.android.gms.common.api.internal.zzcl` not found. It's needed to make sure desugaring of `com.google.android.gms.internal.zzchd` is correct. Desugaring will assume that this interface has no default method.
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbg` was not fo
und, it is required for default or static interface methods desugaring of `boolean com.google.android.gms.internal.zzcfu.equals(java.lang.Object)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.api.internal.zzcm` was no
t found, it is required for default or static interface methods desugaring of `com.google.android.gms.tasks.Task com.google.android.gms.location.FusedLocationProviderClient.
requestLocationUpdates(com.google.android.gms.location.LocationRequest, com.google.android.gms.location.LocationCallback, android.os.Looper)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/ec5c08fd4f4a4a431a34cc9ef156787b/jars/classes.jar: D8: Type `com.google.android.gms.common.api.internal.zzdf` was no
t found, it is required for default or static interface methods desugaring of `com.google.android.gms.tasks.Task com.google.android.gms.location.FusedLocationProviderClient.
removeLocationUpdates(com.google.android.gms.location.LocationCallback)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/46833b0495a661e65aea9bd5c6b857a4/jars/classes.jar: D8: Type `com.google.android.gms.common.util.zzw` was not found, 
it is required for default or static interface methods desugaring of `void com.google.firebase.FirebaseOptions.<init>(java.lang.String, java.lang.String, java.lang.String, j
ava.lang.String, java.lang.String, java.lang.String, java.lang.String)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/46833b0495a661e65aea9bd5c6b857a4/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbq` was not found, it is required for default or static interface methods desugaring of `void com.google.firebase.FirebaseOptions.<init>(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/46833b0495a661e65aea9bd5c6b857a4/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbq` was not found, it is required for default or static interface methods desugaring of `void com.google.firebase.auth.FirebaseAuthException.<init>(java.lang.String, java.lang.String)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/46833b0495a661e65aea9bd5c6b857a4/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbg` was not found, it is required for default or static interface methods desugaring of `boolean com.google.firebase.FirebaseOptions.equals(java.lang.Object)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/46833b0495a661e65aea9bd5c6b857a4/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbq` was not found, it is required for default or static interface methods desugaring of `com.google.firebase.FirebaseOptions$Builder com.google.firebase.FirebaseOptions$Builder.setApiKey(java.lang.String)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/46833b0495a661e65aea9bd5c6b857a4/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbg` was not found, it is required for default or static interface methods desugaring of `boolean com.google.firebase.internal.zzc.equals(java.lang.Object)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/46833b0495a661e65aea9bd5c6b857a4/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzfhg` was not found, it is required for default or static interface methods desugaring of `int com.google.android.gms.internal.zzfkk.zzhs()`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/46833b0495a661e65aea9bd5c6b857a4/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzfhu$zzg` was not found, it is required for default or static interface methods desugaring of `void com.google.android.gms.internal.zzfkl.<clinit>()`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/46833b0495a661e65aea9bd5c6b857a4/jars/classes.jar: D8: Type `com.google.android.gms.internal.zzfko` was not found, it is required for default or static interface methods desugaring of `java.lang.Object com.google.android.gms.internal.zzfkk.zza(int, java.lang.Object, java.lang.Object)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/46833b0495a661e65aea9bd5c6b857a4/jars/classes.jar: D8: Type `com.google.android.gms.common.util.zzu` was not found, it is required for default or static interface methods desugaring of `com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.getInstance()`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/46833b0495a661e65aea9bd5c6b857a4/jars/classes.jar: D8: Interface `com.google.android.gms.internal.zzfje` not found. It's needed to make sure desugaring of `com.google.android.gms.internal.zzfkk$zza` is correct. Desugaring will assume that this interface has no default method.
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/46833b0495a661e65aea9bd5c6b857a4/jars/classes.jar: D8: Interface `com.google.android.gms.common.api.internal.zzl` not found. It's needed to make sure desugaring of `com.google.firebase.zza` is correct. Desugaring will assume that this interface has no default method.
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/46833b0495a661e65aea9bd5c6b857a4/jars/classes.jar: D8: Type `com.google.android.gms.common.api.internal.zzk` was not found, it is required for default or static interface methods desugaring of `com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Context, com.google.firebase.FirebaseOptions, java.lang.String)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/46833b0495a661e65aea9bd5c6b857a4/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbq` was not fo
und, it is required for default or static interface methods desugaring of `com.google.firebase.FirebaseApp com.google.firebase.FirebaseApp.initializeApp(android.content.Cont
ext, com.google.firebase.FirebaseOptions, java.lang.String)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/46833b0495a661e65aea9bd5c6b857a4/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbq` was not fo
und, it is required for default or static interface methods desugaring of `void com.google.firebase.provider.FirebaseInitProvider.attachInfo(android.content.Context, android
.content.pm.ProviderInfo)`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/46833b0495a661e65aea9bd5c6b857a4/jars/classes.jar: D8: Type `com.google.android.gms.common.internal.zzbg` was not fo
und, it is required for default or static interface methods desugaring of `java.lang.String com.google.firebase.FirebaseApp.toString()`
/Users/raskolnikov/.gradle/caches/transforms-2/files-2.1/46833b0495a661e65aea9bd5c6b857a4/jars/classes.jar: D8: Interface `com.google.android.gms.internal.zzfje` not found. 
It's needed to make sure desugaring of `com.google.android.gms.internal.zzfkk` is correct. Desugaring will assume that this interface has no default method.`

**Comment by mikehardy** [comment] 2019-10-30 20:12
I don't see errors, I see warnings. How's your app work?

I think this is a duplicate of something reporting on the react-native-firebase repo, read that thread please, then what do you think? https://github.com/invertase/react-native-firebase/issues/2517

**Comment by souljacker** [comment] 2019-10-31 01:38
Hey @mikehardy , thanks for answering. I read it, and I'm not sure how related the issues are.

I'm not using react-native-firebase directly, maybe it's a dependency of one of the other packages I'm using?

`  "dependencies": {
    "@react-native-community/async-storage": "^1.6.2",
    "invariant": "^2.2.4",
    "react": "16.8.6",
    "react-dom": "^16.11.0",
    "react-native": "0.60.5",
    "react-native-app-auth": "^4.4.0",
    "react-native-fs": "^2.14.1",
    "react-native-onesignal": "^3.3.3",
    "remove": "^0.1.5",
    "styled-components": "^4.4.0",
    "superagent": "^5.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.0",
    "@babel/runtime": "^7.6.0",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.4.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-native-dotenv": "^0.2.0",
    "react-test-renderer": "16.8.6"
  }`

In my case installing device info crashes my app. I don't even have to require it anywhere in the app to mat that happen. Those warnings also go away as soon as I uninstall it.

The app is quite simple, it just communicates with my website api and generate Intentions to post on Instagram.

**Comment by mikehardy** [comment] 2019-10-31 03:15
And when your app crashes, an unfiltered logcat contains something I'm sure, what does it contain as the error? 

Maybe it's a Multidex issue? https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh#L136

All I know is that the example here, and my app in general, spit out all of the stuff you pasted in here and they are warnings, not errors. The example runs, my work project app runs. There's something going on in your project, just not sure what

**Closed** 2020-01-10 20:21 UTC
Labels: feedback-requested
