### ISSUE TITLE
RNDeviceInfo React/RCUtils.h file not found

### ISSUE THREAD

**Issue by isaiasmac** [react-native-community/react-native-device-info#683] opened 2019-06-03 20:19 UTC
I followed the instructions with Cocoapods and without it but I get this error:

Lexical or Preprocessor issue:
'React/RCTUtils.h' file not found.

<img width="1552" alt="Screen Shot 2019-06-03 at 4 14 54 PM" src="https://user-images.githubusercontent.com/2950003/58831692-3c92bf80-861b-11e9-8b17-1fd356168197.png">

**Comment by mikehardy** [comment] 2019-06-03 20:40
Sorry you're having trouble. You didn't follow the issue template though. I have no idea what versions you are using.

Two quick thoughts.
1- clone this repo, and run the example. It works. So if the example works, something is wrong in your project. Not sure what, but the example might show you
2- close XCode, use `npm install react-native-clean-project && react-native clean-project-auto && cd ios && pod install`, reopen XCode, try again. Because...XCode.

**Comment by mikehardy** [comment] 2019-06-03 20:43
I don't believe we currently have issues with this, and I've tested it recently so I'm going to close this, but I'll reopen of course if the example doesn't work or there's something project-specific that is nevertheless this library's fault

**Closed by mikehardy** 2019-06-03 20:43 UTC

**Comment by VitorBrangioni** [comment] 2019-06-12 20:52
Same issue, any solution?

**Comment by VitorBrangioni** [comment] 2019-06-12 21:04
I changed xcode 10 to 9, now i have this issue.  Do you know any solution?

**Comment by brkrtp** [comment] 2019-06-19 12:34
+1 Same issue

**Comment by mikehardy** [comment] 2019-06-19 15:29
More spam @brkrtp  - please provide reproduction based on the example

**Comment by iLyxa3D** [comment] 2019-06-25 13:17
Adding this to Podfile resolve RCUtils.h problem
`pod 'React', :path => '../node_modules/react-native' `
`pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'`

but lead to xCode error
`/Users/admin/Documents/[project]/node_modules/react-native/ReactCommon/cxxreact/JSBundleType.h:10:10: 'folly/Portability.h' file not found`

Do you know why this could happen?

**Comment by mikehardy** [comment] 2019-06-25 13:20
Maybe following the example would help? There are other libs https://github.com/react-native-community/react-native-device-info/blob/master/example/ios/Podfile#L23

**Comment by alexstoyanov** [comment] 2019-07-10 13:54
Anyone found a solution on this? Having the exact same issue. The library worked for me until now. I added a new pod library and device info stopped working giving me 'React/RCTUtils.h' file not found.
