### ISSUE TITLE
NativeModule.RNDeviceInfo is null on RN 0.59.10

### ISSUE THREAD

**Issue by beeremy** [react-native-community/react-native-device-info#748] opened 2019-08-08 21:24 UTC
# Bug
Dear all,

I am upgrading my app from RN 0.53 to RN 0.59.10 and it's been a day I'm facing the following bug after the app successfully compiles:

*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null.

I have upgraded to the package version to the last one (i.e. 2.3.2), I've tried to follow the instructions given, I've tried to unlink, uninstall, install, link, pod install, but still, the issue remains. I've also added the piece of code inside react-native-config.js.

## Environment info

React native info output:

```bash
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i7-6660U CPU @ 2.40GHz
      Memory: 149.80 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.7.0 - /usr/local/Cellar/node/12.7.0/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
      npm: 6.10.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 25.0.1, 25.0.2, 26.0.1, 27.0.3, 28.0.2, 28.0.3
        System Images: a...s_playstore | Google Play Intel x86 Atom Sys...
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Library version: 2.3.2

**Comment by rodrigowpl** [comment] 2019-08-08 21:40
I've having the same issue here, but I'm using RN 0.60.4, this still need to link manually?

**Comment by mikehardy** [comment] 2019-08-08 21:45
@rodrigowpl for RN60 you do not need to link. The example is RN60 and I just closed a similar bug #747 please search for dupes first, that one has the info you need

@beeremy I'm looking into doing a refresh-example-rn59.sh script similar to the one I keep current and corresponding examplern59 test app right now, almost have it working. It *should* work but if it fails that will show the problem.

**Comment by mikehardy** [comment] 2019-08-08 21:57
https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example-rn59.sh

Okay, I have an example just now for RN59, everything works, so I can't reproduce.

I know react-native upgrades are difficult (I just finished moving to RN60, hooboy...) but I don't think this module has a problem with RN59

**Closed by mikehardy** 2019-08-08 21:57 UTC

**Comment by dquessenberry** [comment] 2019-08-16 19:10
I am having this same issue. I just initialized a fresh RN project at v0.59.10, initialized cocoapods (`pod init` in the /ios directory), then installed react-native-device-info via yarn (amongst other modules too). I ran the `react-native link react-native-device-info` command and it added the appropriate RNDeviceInfo pod to my podfile. I executed `pod install`, built the app successfully, but when I run the app I get this same error. 

I ran into this issue yesterday and was able to get it to work by manually linking react-native-device-info even though I am using cocoapods. Because of other odd issues I've been fighting the past week, I decided to initialize a fresh project, yet I am still getting this error. I would prefer NOT to manual link if technically the correct way would be to utilize pods.

**Comment by mikehardy** [comment] 2019-08-16 19:20
well that is most strange, we both did a fresh init and got different results. Thanks for reporting this.

I am guessing when you did the link your Podfile was there based on the steps you describe and the mention of device-info content in the Podfile

I think for RN59 at least with the current release the recommendation must be to run the link before you had a Podfile (or temporarily move it out of the way).

Why? Good question, but when I do a fresh init I know that RN59.10 comes down with no Podfile by default, which triggers a different linking style, and I link that way: https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example-rn59.sh#L31

I think for RN59 the use of pods was experimental (I had [to hack around it](https://github.com/mikehardy/rnfbdemo/blob/master/PodfileRN59#L72) a lot to get it to work with various workarounds depending on included modules) and I recommend manual link (with Podfile not present during link), whereas for RN60 it's the reverse - just add the module and you're done

**Comment by dquessenberry** [comment] 2019-08-16 19:29
@mikehardy that makes sense, actually. Executing `react-native link react-native-device-info` prior to initializing pods (no podfile yet) would effectively add the dependency like the manual linking steps. So I guess with RN <0.60 your choice is to either manually link if you're already using cocoapods or use react-native link if you aren't?

**Comment by mikehardy** [comment] 2019-08-16 19:32
It seems - based on the success of my refresh-example-rn59.sh and the failure of your link-after-pod-init - that you are correct: if using cocoapods with rn59, manually link

*but* - to make it easy at least, I have moved the Podfile out of the way for certain modules and then run link, then moved it back and that automates everything at least. This should probably be documented :sweat_smile: - could you please PR to the install docs mentioning there seems to be a need to work this way, with a link here? :pray:

**Comment by mptorz** [comment] 2019-09-02 15:20
I am facing the same issue. I also updated react-native to 0.59.10 and started experiencing this. Is there any way to get it working without the need of manual linking? What is the latest version of react-native that doesn't have this issue?

**Comment by mikehardy** [comment] 2019-09-02 15:27
If you use react-native <= 0.59.x you must manually link, just like forever. And if you have a podfile, move it out of the way first, or use patch-package to delete the podspec from react-native-device-info until you can move to 0.60 perhaps.

Cocoapods was not officially supported by react-native prior to react-native 0.60 because of problems like this. I have sympathy for the difficulty of moving to react-native 0.60 but as it is unavoidable I am not motivated to hack on fixes for old versions. 

If someone can figure out whatever the problem in the podspec was and wants to make a PR I could maybe branch and do a release on 2.x or similar. But I'm focused on getting v3 out #760 so I can fix App Store warnings, and the 20 other bugs that will be closed out.

**Comment by dquessenberry** [comment] 2019-09-02 16:11
@mptorz, not long after encountering this issue, I decided to upgrade to RN v0.60.5 and no longer have this issue. Although not technically a direct solution, upgrading to 0.60 is such a huge improvement and I highly recommended it if you can. I ran into so many odd issues related to linking/pods with 0.59 and now everything seems to work as expected.

**Comment by mikehardy** [comment] 2019-09-03 14:02
Yes, react-native 60 upgrades are out of scope here but the upgrade-helper site and the CLI do nudge you in the right direction. And yes, you must unlink *almost everything* first. The things you keep are the things where you need the symbols in your code still (like react-native-splash-screen where you have to add code in MainActivity etc)

**Comment by Luckygirlllll** [comment] 2019-10-07 15:01
The same issue, is there any updates about how to fix it?

**Comment by mikehardy** [comment] 2019-10-07 16:24
@Luckygirlllll I just updated the RN59 example script over the weekend to prove / confirm it works, so I'm not sure what the problem is in any specific project, but I know for certain that the current code here (released at the moment as 4.0.1-beta.4, but really any version v3.x and forwards) should work just fine

My best recommendation is to examine that demonstration (possibly clone it and run it) to see how it does what it does, then copy that

https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example-rn59.sh

**Comment by avenyproduction** [comment] 2019-10-09 12:01
I am experiencing the same problem in Android app only. Works great on iOS.
I tried moving out Podfile and linking, but I got message that it is already linked.

**Comment by davidmarinangeli** [comment] 2019-10-29 12:39
@mikehardy after your reply, I checked once again the whole RN Helper from 0.59 to 0.61.2 but the library link stills seems broken. Manual linking in `MainApplication.java` fixed it for me.

**Comment by mikehardy** [comment] 2019-10-29 12:51
Fair enough that it's still happening for you, but it definitely should not be. Something is off in your project if you have to manually link after RN60. Proof, vs words: https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example.sh - what it could be I have no idea, the RN59->RN60 transition was tough enough I'm trying to forget it. But something's missing in your project.

**Comment by davidmarinangeli** [comment] 2019-10-29 14:03
Yeah, I am still facing the transition: I will reply here if I will find something missing in my configuration. Thanks a lot for your time.

**Comment by GrinchakAndrew** [comment] 2019-11-04 21:41
Removing the podfile entry for the lib (  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'), and re-linking manually, as described here: https://github.com/react-native-community/react-native-device-info#linking-for-react-native--059-only-react-native--060-skip-this-as-auto-linking-should-work, worked for RN 59.

**Comment by josephbuchma** [comment] 2019-11-20 15:20
If you have monorepo (like I do with yarn workspaces), make sure `react-native-device-info` is listed in 'package.json' of your RN workspace/subpackage.
Another thing I discovered during migration to RN 60 is that jetifier does not work properly with monorepo too. In order for it to work you have to run in in the root of your monorepo (where hoisted node_modules are located)
